services:
    app.admin.particpante:
        class: AppBundle\Admin\ParticipanteAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Participante" }
        arguments:
            - ~
            - ModelBundle\Entity\Participante
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]