<?php

namespace ModelBundle\Repository;

/**
 * CategoriaVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
