<?php

namespace ModelBundle\Repository;

/**
 * ParticipanteVariableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipanteVariableRepository extends \Doctrine\ORM\EntityRepository
{
}
